// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfnk2uBYKNoPK1pd352f_cXT3PmuxpF4s',
    appId: '1:510651380506:web:893592181a10cab10f32a3',
    messagingSenderId: '510651380506',
    projectId: 'flutter-all-c775a',
    authDomain: 'flutter-all-c775a.firebaseapp.com',
    storageBucket: 'flutter-all-c775a.appspot.com',
    measurementId: 'G-M06GZ3C7M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQZNEgmEEi3GGl6oT-iOTA70Z3w_dKtwU',
    appId: '1:510651380506:android:eda93a6c627eb4810f32a3',
    messagingSenderId: '510651380506',
    projectId: 'flutter-all-c775a',
    storageBucket: 'flutter-all-c775a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoxtSNvJO-lsxXZnN70Adb7s8miK7VXoI',
    appId: '1:510651380506:ios:d863909842092a2e0f32a3',
    messagingSenderId: '510651380506',
    projectId: 'flutter-all-c775a',
    storageBucket: 'flutter-all-c775a.appspot.com',
    iosClientId: '510651380506-ke58vcopogc28nmpkau6k1mk9c1odogs.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterSampleWidyaedu',
  );
}
